[package]
name = "quay-store"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
quay-core.workspace = true
anyhow.workspace = true
tracing.workspace = true
sha2.workspace = true
base64.workspace = true
flate2.workspace = true
tar.workspace = true

[dev-dependencies]
tempfile.workspace = true
